export const QUERY_KEYS = {
  PROPERTIES: "PROPERTIES",
  PROPERTIES_CATEGORIES: "PROPERTIES_CATEGORIES",
  PROPERTIES_CATEGORIES_TYPE: "PROPERTIES_CATEGORIES_TYPE",
  USER_PROFILE: "USER_PROFILE",
  AGREEMENTS: "AGREEMENTS",
  CUSTOMERS: "CUSTOMERS",
  GET_CUSTOMER: "GET_CUSTOMER",
  GET_ACTIVE_CUSTOMERS: "GET_ACTIVE_CUSTOMERS",
  PAYMENTS: 'payments',
  CUSTOMER_PAYMENTS: 'customer-payments',
  USER_PAYMENTS: 'user-payments',
  UTILITY_BILLS: 'utility-bills',
  CUSTOMER_UTILITY_BILLS: 'customer-utility-bills',
  DASHBOARD_STATS: 'dashboard-stats',
};

// Constant declarations

const PROPERTIES_PAGE_SIZE = 1000;

export { PROPERTIES_PAGE_SIZE };
